version: '3'
services:
  wetter_scraper:
    build: .
    container_name: wetter_scraper
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - WETTERCOM_URL=${WETTERCOM_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
